version: "3.9"

services:

  postgres:
    build:
      context: .
      target: db_deploy

  webapp:
    build:
      context: .
      target: webapp_deploy

  importer:
    build:
      context: .
      target: importer_deploy

  reporter:
    build:
      context: .
      target: reporter_deploy

  volumes:
    db-data:
